# Generated by Django 5.2.4 on 2025-08-03 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="habit",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, null=True, verbose_name="Время начала привычки"
            ),
        ),
    ]
